# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Update bot

on:
  push:
    branches: [lab3]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: server
        uses: appleboy/ssh-action@master
        with:
          host: 3.112.219.164
          username: akrestenko
          key: ${{ secrets.SECRET_KEY }}
          script: |
            cd /home/akrestenko/cross-domain-recsys/
            sudo git pull
            sudo rebuild.bash